version: '3.4'

services:
  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - healthcheck

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - healthcheck

  grafana:
    image: grafana/grafana #grafana/grafana:5.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - healthcheck

networks:
  healthcheck:
    driver: bridge